const data = [
    {
      id: '9s41rp',
      Patientname: 'Josh Clark',
      DOB: '05-04-1992',
      OpenMeasure:'02',
      RiskPatient:'all',
      hub: 'Ohio',
    },
    {
      id: '08m6rx',
      Patientname: 'amit Clark',
      DOB: '07-04-1992',
      OpenMeasure:'02',
      RiskPatient:'all',
      hub: 'Ohio',
    },
    {
      id: '5ymtrc',
      Patientname: 'Josh Clark',
      DOB: '08-04-1992',
      OpenMeasure:'02',
      RiskPatient:'all',
      hub: 'Ohio',
    },
    {
      id: 'xxtydd',
      Patientname: 'Josh Clark',
      DOB: '05-04-1992',
      OpenMeasure:'02',
      RiskPatient:'all',
      hub: 'Ohio',
    },
    {
      id: 'wzxj9m',
      Patientname: 'Josh Clark',
      DOB: '05-04-1992',
      OpenMeasure:'02',
      RiskPatient:'all',
      hub: 'Ohio',
    },
    {
      id: '21dwtz',
      Patientname: 'Josh Clark',
      DOB: '05-04-1992',
      OpenMeasure:'02',
      RiskPatient:'all',
      hub: 'Ohio',
    },
    {
      id: 'o8oe4kln',
      Patientname: 'Josh Clark',
      DOB: '05-04-1992',
      OpenMeasure:'02',
      RiskPatient:'all',
      hub: 'Ohio',
    },
    {
      id: 'o8oe4kef',
      Patientname: 'Josh Clark',
      DOB: '05-04-1992',
      OpenMeasure:'02',
      RiskPatient:'all',
      hub: 'Ohio',
    },
    {
      id: 'o8oe4kjf',
      Patientname: 'Josh Clark',
      DOB: '05-04-1992',
      OpenMeasure:'02',
      RiskPatient:'all',
      hub: 'Ohio',
    },
    {
      id: 'o8oe4kfr',
      Patientname: 'Josh Clark',
      DOB: '05-04-1992',
      OpenMeasure:'02',
      RiskPatient:'all',
      hub: 'Ohio',
    },
    {
      id: 'o8oe4kll',
      Patientname: 'Josh Clark',
      DOB: '05-04-1992',
      OpenMeasure:'02',
      RiskPatient:'all',
      hub: 'Ohio',
    },
    {
      id: 'o8oe4km',
      Patientname: 'Josh Clark',
      DOB: '05-04-1992',
      OpenMeasure:'02',
      RiskPatient:'all',
      hub: 'Ohio',
    },
    
  ];
  
  module.exports = { data};
  