const data = [
    {
      id: '9s41rp',
      Measure: 'Measure1',
      Description: 'Langosh',
      ApplicableProvider: 'All',
      RequiresScheduling: 19,
      RequiresVisit:'lorem',
      RequiresTemplate:'all',
      ActiveFlag: 'Ohio',
    },
    {
      id: '08m6rx',
      Measure: 'Measure1',
      Description: 'Purdy',
      ApplicableProvider: 'All',
      RequiresScheduling: 37,
      RequiresVisit:'lorem',
      RequiresTemplate:'all',
      state: 'Rhode Island',
    },
    {
      id: '5ymtrc',
      Measure: 'Measure1',
      Description: 'Lynch',
      ApplicableProvider: 'All',
      RequiresScheduling: 20,
      RequiresVisit:'lorem',
      RequiresTemplate:'all',
      ActiveFlag: 'California',
    },
    {
      id: 'ek5b97',
      Measure: 'Measure1',
      Description: 'Douglas',
      ApplicableProvider: 'All',
      RequiresScheduling: 38,
      RequiresVisit:'lorem',
      RequiresTemplate:'all',
      ActiveFlag: 'Montana',
    },
    {
      id: 'xxtydd',
      Measure: 'Measure1',
      Description: 'Williamson',
      ApplicableProvider: 'All',
      RequiresScheduling: 19,
      RequiresVisit:'lorem',
      RequiresTemplate:'all',
      ActiveFlag: 'Colorado',
    },
    {
      id: 'wzxj9m',
      Measure: 'Measure1',
      Description: 'Friesen',
      ApplicableProvider: 'All',
      RequiresScheduling: 34,
      RequiresVisit:'lorem',
      RequiresTemplate:'all',
      ActiveFlag: 'New York',
    },
    {
      id: '21dwtz',
      Measure: 'Measure1',
      Description: 'Jast',
      ApplicableProvider: 'All',
      RequiresScheduling: 23,
      RequiresVisit:'lorem',
      RequiresTemplate:'all',
      ActiveFlag: 'Montana',
    },
    {
      id: 'o8oe4k',
      Measure: 'Measure1',
      Description: 'Willms',
      ApplicableProvider: 'All',
      RequiresScheduling: 25,
      RequiresVisit:'lorem',
      RequiresTemplate:'all',
      ActiveFlag: 'Nebraska',
    },
    {
      id: 'o8oe4k',
      Measure: 'Measure1',
      Description: 'Willms',
      ApplicableProvider: 'All',
      RequiresScheduling: 25,
      RequiresVisit:'lorem',
      RequiresTemplate:'all',
      ActiveFlag: 'Nebraska',
    },
    {
      id: 'o8oe4k',
      Measure: 'Measure1',
      Description: 'Willms',
      ApplicableProvider: 'All',
      RequiresScheduling: 25,
      RequiresVisit:'lorem',
      RequiresTemplate:'all',
      ActiveFlag: 'Nebraska',
    },
    {
      id: 'o8oe4k',
      Measure: 'Measure1',
      Description: 'Willms',
      ApplicableProvider: 'All',
      RequiresScheduling: 25,
      RequiresVisit:'lorem',
      RequiresTemplate:'all',
      ActiveFlag: 'Nebraska',
    },
    {
      id: 'o8oe4k',
      Measure: 'Measure1',
      Description: 'Willms',
      ApplicableProvider: 'All',
      RequiresScheduling: 25,
      RequiresVisit:'lorem',
      RequiresTemplate:'all',
      ActiveFlag: 'Nebraska',
    },
    {
      id: 'o8oe4k',
      Measure: 'Measure1',
      Description: 'Willms',
      ApplicableProvider: 'All',
      RequiresScheduling: 25,
      RequiresVisit:'lorem',
      RequiresTemplate:'all',
      ActiveFlag: 'Nebraska',
    },
    {
      id: 'o8oe4k',
      Measure: 'Measure1',
      Description: 'Willms',
      ApplicableProvider: 'All',
      RequiresScheduling: 25,
      RequiresVisit:'lorem',
      RequiresTemplate:'all',
      ActiveFlag: 'Nebraska',
    },
    {
      id: 'o8oe4k',
      Measure: 'Measure1',
      Description: 'Willms',
      ApplicableProvider: 'All',
      RequiresScheduling: 25,
      RequiresVisit:'lorem',
      RequiresTemplate:'all',
      ActiveFlag: 'Nebraska',
    },
    {
      id: 'o8oe4k',
      Measure: 'Measure1',
      Description: 'Willms',
      ApplicableProvider: 'All',
      RequiresScheduling: 25,
      RequiresVisit:'lorem',
      RequiresTemplate:'all',
      ActiveFlag: 'Nebraska',
    },
  ];
  module.exports = { data };
  